<?php

namespace ArrayPress\Stripe;

use Exception;
use Stripe\Account;
use Stripe\AccountLink;
use WP_Error;

/**
 * Accounts
 *
 * Manages Stripe Connect Express connected accounts for affiliate and seller
 * payouts. Handles account creation, Stripe-hosted onboarding, status checking,
 * and account management.
 *
 * Typical affiliate onboarding flow:
 *   1. create()              — Create the connected account
 *   2. create_onboarding_link() — Generate the Stripe-hosted onboarding URL
 *   3. Redirect affiliate to the URL
 *   4. Affiliate completes Stripe's onboarding (KYC, bank details, tax forms)
 *   5. Affiliate redirected to your return_url
 *   6. is_ready()            — Check charges_enabled + payouts_enabled
 *   7. If not ready, create_onboarding_link() again (link is single-use)
 *
 * Once ready, use Transfers to send commission payments.
 *
 * @package ArrayPress\Stripe
 * @since   1.0.0
 */
class Accounts {

	/**
	 * The Stripe client instance.
	 *
	 * @var Client
	 */
	private Client $client;

	/**
	 * Constructor.
	 *
	 * @param Client $client The Stripe client instance.
	 */
	public function __construct( Client $client ) {
		$this->client = $client;
	}

	// -------------------------------------------------------------------------
	// Account Creation & Retrieval
	// -------------------------------------------------------------------------

	/**
	 * Create a new Express connected account.
	 *
	 * Creates the account shell. The affiliate must then complete onboarding
	 * via the link generated by create_onboarding_link() before they can
	 * receive payouts.
	 *
	 * @param array $args Optional prefill data to simplify onboarding:
	 *                    - email       (string) Account holder's email address.
	 *                    - country     (string) Two-letter ISO country code (e.g. 'GB'). Default 'US'.
	 *                    - business_type (string) 'individual' or 'company'. Default 'individual'.
	 *                    - individual  (array)  Prefill: first_name, last_name, email, phone.
	 *                    - business_profile (array) Prefill: url, name, mcc.
	 *                    - metadata    (array)  Arbitrary key/value metadata.
	 *                    - capabilities (array) Requested capabilities. Default: transfers.
	 *
	 * @return Account|WP_Error
	 * @since 1.0.0
	 */
	public function create( array $args = [] ): Account|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			$params = [
				'type'         => 'express',
				'country'      => $args['country'] ?? 'US',
				'capabilities' => $args['capabilities'] ?? [
						'transfers' => [ 'requested' => true ],
					],
			];

			foreach ( [ 'email', 'business_type', 'individual', 'business_profile', 'metadata' ] as $field ) {
				if ( isset( $args[ $field ] ) ) {
					$params[ $field ] = $args[ $field ];
				}
			}

			return $stripe->accounts->create( $params );
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	/**
	 * Retrieve a connected account by ID.
	 *
	 * @param string $account_id Stripe connected account ID (acct_xxx).
	 *
	 * @return Account|WP_Error
	 * @since 1.0.0
	 */
	public function get( string $account_id ): Account|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			return $stripe->accounts->retrieve( $account_id );
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	/**
	 * Update a connected account's details.
	 *
	 * @param string $account_id Stripe connected account ID (acct_xxx).
	 * @param array  $args       Fields to update: email, business_profile, metadata, etc.
	 *
	 * @return Account|WP_Error
	 * @since 1.0.0
	 */
	public function update( string $account_id, array $args ): Account|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			return $stripe->accounts->update( $account_id, $args );
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	/**
	 * Delete a connected account.
	 *
	 * Permanently removes the account. Only works on accounts that have
	 * no active balance. Use with extreme caution.
	 *
	 * @param string $account_id Stripe connected account ID (acct_xxx).
	 *
	 * @return true|WP_Error
	 * @since 1.0.0
	 */
	public function delete( string $account_id ): true|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			$stripe->accounts->delete( $account_id );

			return true;
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	/**
	 * List connected accounts.
	 *
	 * @param array $params Optional: limit (int), starting_after (string), ending_before (string).
	 *
	 * @return array|WP_Error [ 'items' => Account[], 'has_more' => bool, 'cursor' => string ]
	 * @since 1.0.0
	 */
	public function list( array $params = [] ): array|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			$response = $stripe->accounts->all( $params );

			return [
				'items'    => $response->data,
				'has_more' => $response->has_more,
				'cursor'   => ! empty( $response->data ) ? end( $response->data )->id : '',
			];
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	// -------------------------------------------------------------------------
	// Onboarding
	// -------------------------------------------------------------------------

	/**
	 * Create a Stripe-hosted onboarding link for a connected account.
	 *
	 * Account links are single-use and expire quickly. Generate a new one
	 * each time you need to send an affiliate into the onboarding flow.
	 *
	 * The refresh_url is called when the link has expired or been used.
	 * Your page at this URL should generate a new link and redirect the
	 * affiliate back to Stripe.
	 *
	 * The return_url is where Stripe redirects after the affiliate completes
	 * or leaves the flow. It does NOT mean onboarding is complete — always
	 * call is_ready() after the affiliate returns to verify their status.
	 *
	 * @param string $account_id  Stripe connected account ID (acct_xxx).
	 * @param string $return_url  URL to redirect to after onboarding flow.
	 * @param string $refresh_url URL to redirect to if the link expires. Should regenerate the link.
	 * @param string $type        Link type: 'account_onboarding' (new) or 'account_update' (existing). Default 'account_onboarding'.
	 *
	 * @return AccountLink|WP_Error
	 * @since 1.0.0
	 */
	public function create_onboarding_link( string $account_id, string $return_url, string $refresh_url, string $type = 'account_onboarding' ): AccountLink|WP_Error {
		$stripe = $this->client->stripe();

		if ( ! $stripe ) {
			return new WP_Error( 'not_configured', __( 'Stripe client is not configured.', 'arraypress' ) );
		}

		try {
			return $stripe->accountLinks->create( [
				'account'     => $account_id,
				'return_url'  => $return_url,
				'refresh_url' => $refresh_url,
				'type'        => $type,
			] );
		} catch ( Exception $e ) {
			return new WP_Error( 'stripe_error', $e->getMessage() );
		}
	}

	/**
	 * Get the onboarding URL for a connected account (convenience wrapper).
	 *
	 * @param string $account_id  Stripe connected account ID (acct_xxx).
	 * @param string $return_url  URL to redirect to after onboarding flow.
	 * @param string $refresh_url URL to redirect to if the link expires.
	 *
	 * @return string|WP_Error The onboarding URL, or WP_Error on failure.
	 * @since 1.0.0
	 */
	public function get_onboarding_url( string $account_id, string $return_url, string $refresh_url ): string|WP_Error {
		$link = $this->create_onboarding_link( $account_id, $return_url, $refresh_url );

		if ( is_wp_error( $link ) ) {
			return $link;
		}

		return $link->url;
	}

	// -------------------------------------------------------------------------
	// Status Checking
	// -------------------------------------------------------------------------

	/**
	 * Check if a connected account is fully onboarded and ready to receive payouts.
	 *
	 * Always call this after an affiliate returns from the onboarding flow.
	 * A return from Stripe does not guarantee completion — the affiliate may
	 * have saved and exited partway through.
	 *
	 * @param string $account_id Stripe connected account ID (acct_xxx).
	 *
	 * @return bool|WP_Error True if charges_enabled AND payouts_enabled, false otherwise.
	 * @since 1.0.0
	 */
	public function is_ready( string $account_id ): bool|WP_Error {
		$account = $this->get( $account_id );

		if ( is_wp_error( $account ) ) {
			return $account;
		}

		return $account->charges_enabled && $account->payouts_enabled;
	}

	/**
	 * Get a structured status summary for a connected account.
	 *
	 * Useful for displaying onboarding progress in your admin UI or
	 * deciding whether to prompt the affiliate to complete onboarding.
	 *
	 * @param string $account_id Stripe connected account ID (acct_xxx).
	 *
	 * @return array|WP_Error {
	 *     @type string $account_id        The connected account ID.
	 *     @type bool   $charges_enabled   Whether the account can process charges.
	 *     @type bool   $payouts_enabled   Whether the account can receive payouts.
	 *     @type bool   $is_ready          True if both charges and payouts are enabled.
	 *     @type bool   $details_submitted Whether the account has submitted onboarding details.
	 *     @type array  $requirements      Outstanding requirements (currently_due, eventually_due).
	 *     @type string $email             Account email address.
	 * }
	 * @since 1.0.0
	 */
	public function get_status( string $account_id ): array|WP_Error {
		$account = $this->get( $account_id );

		if ( is_wp_error( $account ) ) {
			return $account;
		}

		return [
			'account_id'        => $account->id,
			'charges_enabled'   => $account->charges_enabled,
			'payouts_enabled'   => $account->payouts_enabled,
			'is_ready'          => $account->charges_enabled && $account->payouts_enabled,
			'details_submitted' => $account->details_submitted,
			'requirements'      => [
				'currently_due'   => $account->requirements->currently_due ?? [],
				'eventually_due'  => $account->requirements->eventually_due ?? [],
				'past_due'        => $account->requirements->past_due ?? [],
				'disabled_reason' => $account->requirements->disabled_reason ?? '',
			],
			'email'             => $account->email ?? '',
		];
	}

}